/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-02 08:24:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.drama;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.ibatis.reflection.SystemMetaObject;
import com.semi.flix.common.Pager;
import com.semi.flix.drama.DramaDto;
import java.util.List;
import com.semi.flix.common.StringUtil;

public final class drama_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/drama/../include/header.jsp", Long.valueOf(1646201318569L));
    _jspx_dependants.put("/WEB-INF/views/drama/../include/footer.jsp", Long.valueOf(1646199571048L));
    _jspx_dependants.put("/WEB-INF/views/drama/../include/css.jsp", Long.valueOf(1645873405726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("com.semi.flix.drama.DramaDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.semi.flix.common.StringUtil");
    _jspx_imports_classes.add("com.semi.flix.common.Pager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- Font -->\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600%7CUbuntu:300,400,500,700\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("	<!-- CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/bootstrap-reboot.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/bootstrap-grid.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/nouislider.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/plyr.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/photoswipe.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/default-skin.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Favicons -->\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"icon/favicon-32x32.png\" sizes=\"32x32\">\r\n");
      out.write("	<link rel=\"apple-touch-icon\" href=\"icon/favicon-32x32.png\">\r\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"icon/apple-touch-icon-72x72.png\">\r\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"icon/apple-touch-icon-114x114.png\">\r\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"icon/apple-touch-icon-144x144.png\">\r\n");
      out.write("\r\n");
      out.write("	<meta name=\"description\" content=\"\">\r\n");
      out.write("	<meta name=\"keywords\" content=\"\">\r\n");
      out.write("	<meta name=\"author\" content=\"Dmitry Volkov\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- JS -->\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/jquery.mousewheel.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/jquery.mCustomScrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/wNumb.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/nouislider.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/plyr.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/jquery.morelines.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/photoswipe.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/photoswipe-ui-default.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/main.js\"></script>");
      out.write("\r\n");
      out.write("	<title>FlixGo – Online Movies, TV Shows & Cinema HTML Template</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"body\">\r\n");
      out.write("	");

	String key = StringUtil.nullToValue(request.getParameter("key"), "7");
	String keyword = StringUtil.nullToValue(request.getParameter("keyword"), "");
	String pg = StringUtil.nullToValue(request.getParameter("pg"), "0");
	int totalCnt = (Integer)request.getAttribute("totalCnt");
	List<DramaDto> list =(List<DramaDto>)request.getAttribute("dramaList");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');

request.setAttribute("commonURL", request.getContextPath());

      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\"> \r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"header__wrap\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<div class=\"header__content\">\r\n");
      out.write("							<!-- header logo -->\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/home\" class=\"header__logo\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.svg\" alt=\"\">\r\n");
      out.write("							</a>\r\n");
      out.write("							<!-- end header logo -->\r\n");
      out.write("\r\n");
      out.write("							<!-- header nav -->\r\n");
      out.write("							<ul class=\"header__nav\">\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"pricing.html\" class=\"header__nav-link\">영화</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drama/list\" class=\"header__nav-link\">드라마</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"pricing.html\" class=\"header__nav-link\">예능</a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"faq.html\" class=\"header__nav-link\">애니메이션</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/webtoon/list\" class=\"header__nav-link\">웹툰</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"header__nav-item\">\r\n");
      out.write("									<a href=\"faq.html\" class=\"header__nav-link\">도서</a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<!-- dropdown -->\r\n");
      out.write("								<li class=\"dropdown header__nav-item\">\r\n");
      out.write("									<a class=\"dropdown-toggle header__nav-link header__nav-link--more\" href=\"#\" role=\"button\" id=\"dropdownMenuMore\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"icon ion-ios-more\"></i></a>\r\n");
      out.write("\r\n");
      out.write("									<ul class=\"dropdown-menu header__dropdown-menu\" aria-labelledby=\"dropdownMenuMore\">\r\n");
      out.write("										<li><a href=\"about.html\">영화</a></li>\r\n");
      out.write("										<li><a href=\"signin.html\">예능</a></li>\r\n");
      out.write("										<li><a href=\"signup.html\">드라마</a></li>\r\n");
      out.write("										<li><a href=\"404.html\">만화</a></li>\r\n");
      out.write("										<li><a href=\"404.html\">웹툰</a></li>\r\n");
      out.write("										<li><a href=\"404.html\">도서</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</li>\r\n");
      out.write("								<!-- end dropdown -->\r\n");
      out.write("							</ul>\r\n");
      out.write("							<!-- end header nav -->\r\n");
      out.write("\r\n");
      out.write("							<!-- header auth -->\r\n");
      out.write("							<div class=\"header__auth\">\r\n");
      out.write("								<button class=\"header__search-btn\" type=\"button\">\r\n");
      out.write("									<i class=\"icon ion-ios-search\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("\r\n");
      out.write("								<a class=\"header__sign-in\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signin\">\r\n");
      out.write("									<i class=\"icon ion-ios-log-in\"></i>\r\n");
      out.write("									<span>sign in</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- end header auth -->\r\n");
      out.write("\r\n");
      out.write("							<!-- header menu btn -->\r\n");
      out.write("							<button class=\"header__btn\" type=\"button\">\r\n");
      out.write("								<span></span>\r\n");
      out.write("								<span></span>\r\n");
      out.write("								<span></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<!-- end header menu btn -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- header search -->\r\n");
      out.write("		<form action=\"#\" class=\"header__search\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<div class=\"header__search-content\">\r\n");
      out.write("							<input type=\"text\" placeholder=\"Search for a movie, TV Series that you are looking for\">\r\n");
      out.write("\r\n");
      out.write("							<button type=\"button\">search</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- end header search -->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- end header -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- page title -->\r\n");
      out.write("	<section class=\"section section--first section--bg\" data-bg=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/section/section.jpg\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div class=\"section__wrap\">\r\n");
      out.write("						<!-- section title -->\r\n");
      out.write("						<h2 class=\"section__title\">드라마(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("건)</h2>\r\n");
      out.write("						<!-- end section title -->\r\n");
      out.write("\r\n");
      out.write("						<!-- breadcrumb -->\r\n");
      out.write("						\r\n");
      out.write("						<!-- end breadcrumb -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- end page title -->\r\n");
      out.write("<form name=\"myform\" method=\"get\">\r\n");
      out.write("	<input type=\"hidden\" name=\"pg\"  id=\"pg\" value=\"");
      out.print(pg);
      out.write("\"/>\r\n");
      out.write("	<input type=\"hidden\" name=\"key\" id=\"key\" value=\"");
      out.print(key);
      out.write("\"/>\r\n");
      out.write("	<input type=\"hidden\" name=\"board_seq\"  id=\"board_seq\" value=\"\"/>\r\n");
      out.write("		<!-- filter -->\r\n");
      out.write("		<div class=\"filter\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<div class=\"filter__content\">\r\n");
      out.write("							<div class=\"filter__items\">\r\n");
      out.write("								<!-- filter item -->\r\n");
      out.write("								<div class=\"filter__item\" id=\"filter__genre\">\r\n");
      out.write("									<span class=\"filter__item-label\">GENRE:</span>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"filter__item-btn dropdown-toggle\" role=\"navigation\" id=\"filter-genre\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("										<input type=\"button\" value=\"선택하세요\" id=\"searchItem\">\r\n");
      out.write("										\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<ul class=\"filter__item-menu dropdown-menu scrollbar-dropdown\" aria-labelledby=\"filter-genre\">\r\n");
      out.write("										\r\n");
      out.write("										<li><a onclick=\"changeSearch('7')\">전체</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('0')\">Action</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('1')\">Romance</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('2')\">Comedy</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('3')\">Thriller/Crime</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('4')\">Horror</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('5')\">Fantasy</a></li>\r\n");
      out.write("										<li><a onclick=\"changeSearch('6')\">Drama</a></li>\r\n");
      out.write("										\r\n");
      out.write("									</ul>\r\n");
      out.write("									<button class=\"sign__btn\" type=\"button\" onclick=\"goSearch()\" \r\n");
      out.write("											style=\"width:100px; height: 30px; margin:2px;\">검색</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- end filter item -->\r\n");
      out.write("	\r\n");
      out.write("								<!-- filter item -->\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<!-- filter btn -->\r\n");
      out.write("							<button class=\"filter__btn\" type=\"button\">apply filter</button>\r\n");
      out.write("							<!-- end filter btn -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- end filter -->\r\n");
      out.write("	\r\n");
      out.write("		<!-- catalog -->\r\n");
      out.write("		<div class=\"catalog\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<!-- card -->\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					");
for(DramaDto dto : list){
					System.out.println("---------------------------------"+dto.getBoard_seq());
					System.out.println("---------------------------------"+dto.getDrama_title());
					
      out.write("\r\n");
      out.write("					<div class=\"col-6 col-sm-4 col-lg-3 col-xl-2\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card__cover\">\r\n");
      out.write("							\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commonURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/drama_img/");
      out.print(dto.getDrama_images() );
      out.write("\" style=\"height: 230px;object-fit: cover;\">\r\n");
      out.write("								<a href=\"#\" class=\"card__play\" onclick=\"goView('");
      out.print(dto.getBoard_seq());
      out.write("')\">\r\n");
      out.write("									\r\n");
      out.write("								</a>\r\n");
      out.write("						\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card__content\">\r\n");
      out.write("							\r\n");
      out.write("								<h3 class=\"card__title\"><a href=\"#\" onclick=\"goView('");
      out.print(dto.getBoard_seq());
      out.write("')\">");
      out.print(dto.getDrama_title() );
      out.write("</a></h3>\r\n");
      out.write("								<span class=\"card__category\">\r\n");
      out.write("								");

								if(dto.getGenre_code().equals("00")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Action</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("01")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Romantic</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("02")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Comedy</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("03")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Thliler/Criminal</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("04")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Horror</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("05")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">SF/Fantasy</a>\r\n");
      out.write("									");
}else if(dto.getGenre_code().equals("06")){ 
      out.write("\r\n");
      out.write("									<a href=\"#\">Drama</a>\r\n");
      out.write("									");
}
      out.write("\r\n");
      out.write("									\r\n");
      out.write("								</span>\r\n");
      out.write("								<span class=\"card__rate\"><i class=\"icon ion-ios-star\"></i>8.4</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("					<!-- end card -->\r\n");
      out.write("	\r\n");
      out.write("				\r\n");
      out.write("	\r\n");
      out.write("					<!-- paginator -->\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						");
      out.print(Pager.makeTag(request, 12, totalCnt) );
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- end paginator -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- end catalog -->\r\n");
      out.write("</form>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\"> \r\n");
      out.write("<!-- partners -->\r\n");
      out.write("	<section class=\"section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- section title -->\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<h2 class=\"section__title section__title--no-margin\">Our Partners</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end section title -->\r\n");
      out.write("\r\n");
      out.write("				<!-- section text -->\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<p class=\"section__text section__text--last-with-margin\">It is a long <b>established</b> fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end section text -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/themeforest-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/audiojungle-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/codecanyon-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/photodune-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/activeden-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("\r\n");
      out.write("				<!-- partner -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("					<a href=\"#\" class=\"partner\">\r\n");
      out.write("						<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/partners/3docean-light-background.png\" alt=\"\" class=\"partner__img\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end partner -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- end partners -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- footer list -->\r\n");
      out.write("				<div class=\"col-12 col-md-3\">\r\n");
      out.write("					<h6 class=\"footer__title\">Download Our App</h6>\r\n");
      out.write("					<ul class=\"footer__app\">\r\n");
      out.write("						<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/Download_on_the_App_Store_Badge.svg\" alt=\"\"></a></li>\r\n");
      out.write("						<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/google-play-badge.png\" alt=\"\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end footer list -->\r\n");
      out.write("\r\n");
      out.write("				<!-- footer list -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("					<h6 class=\"footer__title\">Resources</h6>\r\n");
      out.write("					<ul class=\"footer__list\">\r\n");
      out.write("						<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("						<li><a href=\"#\">Pricing Plan</a></li>\r\n");
      out.write("						<li><a href=\"#\">Help</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end footer list -->\r\n");
      out.write("\r\n");
      out.write("				<!-- footer list -->\r\n");
      out.write("				<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("					<h6 class=\"footer__title\">Legal</h6>\r\n");
      out.write("					<ul class=\"footer__list\">\r\n");
      out.write("						<li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("						<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						<li><a href=\"#\">Security</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end footer list -->\r\n");
      out.write("\r\n");
      out.write("				<!-- footer list -->\r\n");
      out.write("				<div class=\"col-12 col-sm-4 col-md-3\">\r\n");
      out.write("					<h6 class=\"footer__title\">Contact</h6>\r\n");
      out.write("					<ul class=\"footer__list\">\r\n");
      out.write("						<li><a href=\"tel:+18002345678\">+1 (800) 234-5678</a></li>\r\n");
      out.write("						<li><a href=\"mailto:support@moviego.com\">support@flixgo.com</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"footer__social\">\r\n");
      out.write("						<li class=\"facebook\"><a href=\"#\"><i class=\"icon ion-logo-facebook\"></i></a></li>\r\n");
      out.write("						<li class=\"instagram\"><a href=\"#\"><i class=\"icon ion-logo-instagram\"></i></a></li>\r\n");
      out.write("						<li class=\"twitter\"><a href=\"#\"><i class=\"icon ion-logo-twitter\"></i></a></li>\r\n");
      out.write("						<li class=\"vk\"><a href=\"#\"><i class=\"icon ion-logo-vk\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end footer list -->\r\n");
      out.write("\r\n");
      out.write("				<!-- footer copyright -->\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div class=\"footer__copyright\">\r\n");
      out.write("						<small><a target=\"_blank\" href=\"https://www.templateshub.net\">Templates Hub</a></small>\r\n");
      out.write("\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end footer copyright -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("		<!-- JS -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("	let key = '");
      out.print(key);
      out.write("';\r\n");
      out.write("	var texts=[\"Action\", \"Romance\", \"Comedy\", \"Thriller/Crime\", \"Horror\",\"Fantasy\",\"Drama\",\"전체\"];\r\n");
      out.write("	\r\n");
      out.write("	document.getElementById(\"searchItem\").value=texts[key];\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeSearch(id)\r\n");
      out.write("{\r\n");
      out.write("	var texts=[\"Action\", \"Romance\", \"Comedy\", \"Thriller/Crime\", \"Horror\",\"Fantasy\",\"Drama\",\"전체\"];\r\n");
      out.write("	document.getElementById(\"searchItem\").value=texts[id]; //화면에 보이기 위해서 \r\n");
      out.write("	document.getElementById(\"key\").value=id;//컨트롤러로 넘기기 위해서\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goSearch(){\r\n");
      out.write("	let frm = document.myform;\r\n");
      out.write("	frm.pg.value=0;\r\n");
      out.write("	frm.action = \"");
      out.print(request.getContextPath());
      out.write("/drama/list\";\r\n");
      out.write("	frm.method=\"get\";\r\n");
      out.write("	frm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goView(id)\r\n");
      out.write("{\r\n");
      out.write("	\r\n");
      out.write("	frm = document.myform;\r\n");
      out.write("	frm.board_seq.value=id;///////////\r\n");
      out.write("	frm.method=\"get\";\r\n");
      out.write("	frm.action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drama/view\";\r\n");
      out.write("	frm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goPage(pg)\r\n");
      out.write("{\r\n");
      out.write("	frm = document.myform;\r\n");
      out.write("	frm.pg.value=pg;///////////\r\n");
      out.write("	frm.method=\"get\";\r\n");
      out.write("	frm.action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drama/list\";\r\n");
      out.write("	frm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
